%define TEXT_BUFFER 0xb8000

%define WHITE_RED       0x4f
%define RED_WHITE       0xf4

%define WHITE_GREEN     0xF2
%define GREEN_WHITE     0x2F

%define YELLOW_WHITE    0xEF
%define WHITE_YELLOW    0xFE
%define BLACK_YELLOW    0x0E

%define WHITE_BLACK     0xF0
%define BLACK_WHITE     0x0F

%define LIGHT_GRAY__WHITE 0x7F
%define WHITE__LIGHT_GRAY 0xF7
%define LIGHT_GRAY__BLACK 0x70

%define DARK_GRAY__WHITE 0x8F
%define WHITE__DARK_GRAY 0xF8
%define LIGHT_GRAY__BLACK 0x80

%define RAW_BLUE 0x11
%define RAW_RED 0x44
%define RAW_BLACK 0x00

%define WHITE_BLUE 0xF1
%define WHITE_RED 0xF4
%define BLUE_WHITE 0x1F
%define WHITE_BLUE 0x1F
%define RED_WHITE 0x4F

%define CHARACTERS_PER_LINE 80
%define LINES_PER_SCREEN 25